### ISSUE TITLE
Create an on boarding document

### ISSUE THREAD

**Issue by gregboyer** [codeforamerica/brigade-project-index#11]
Create an on boarding document for introducing new members, establishing important links and documents, and acting as a living document for decisions etc.

**Comment by ExperimentsInHonesty** [comment]
Is this going to be the readme on this repo?  Or should we make a Wiki?

**Comment by gregboyer** [comment]
Team: Will start as a readme

**Comment by gregboyer** [comment]
More to follow, but first draft is here on the wiki. Please review and add content/suggestions as necessary: 
https://github.com/codeforamerica/brigade-project-index/pull/16

**Comment by ExperimentsInHonesty** [comment]
Fixes #16
