### ISSUE TITLE
Review new proposal: use Github for the first version of project index

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [codeforamerica/brigade-project-index#15]
### Overview
After some in-depth analysis of what is possible with github tools, I propose we use it and a topic/status and label/needs taxonomy as our MVP. 

### Details
If we can get brigades to use the tools that are already built into Github for project descriptions, and topic tags, our project code will need to do less and we can start creating a searchable resource now, without any coding.   And if we still want to build something bigger after launch we can use the github API to get the real time data that these tags hold. 

I created a [workshop outline](https://docs.google.com/document/d/1pkhun4Z1Wxa2qtUGqQFLDq-ylx59YiwEzG9Rx35RgBc/edit#) that focused on two basic meta tagging features:
![image](https://user-images.githubusercontent.com/37763229/62113972-81795200-b26a-11e9-83e5-13d6fde424c2.png)

The important takeaways from the research that I did (that prompted the creation of the workshop) were:
- These changes are easy and fast to make.  I updated one of our projects myself in the time it has taken you to read to this point in this issue.
- Everyone can understand how to make the changes even if they don't consider themselves technical.
- The repository changes have benefits beyond project index
   - search engine optimization
   - social media appearance of project links
- The changes bring Immediate value to brigade leadership (being able to provide one link to volunteers that connects them with all the repos), if your brigade is like ours and the projects are sometimes not housed inside our Github organization account.  Here are some examples from our brigade:
  - github.com/hackforla (main org account)
  - github.com/helloGov 
  - github.com/hfla-engage 
  - github.com/Public-Tree-Map
  - github.com/metro-ontime
  - and many others
- It address 57% of the use stories (15 our of 26).  I added asterisks to user stories covered.
  - It address 12 of the 26 User Stories without a line of code and without perverting the intention of the topics tag (as defined by github).
  - It could address 3 additional user stories if we used the topic tag to address status, but we would need a solid taxonomy with details about how to qualify projects for each status.
  - It could address 4 of the user stories well, if we encouraged the proper use of labels on issues.
  - It address all of Tom Dooner's user stories
- Its a good team building exercise
- It gives us something to do real UX on, because we would have an actual searchable code-for-america project index, and we could ask people to try it and tell us what else they need it to do, instead of us trying to build the ultimate tool and tons of documentation it is going to take to implement it before we have talked to anyone outside this circle.

### Action items:
- review this Github [workshop outline](https://docs.google.com/document/d/1pkhun4Z1Wxa2qtUGqQFLDq-ylx59YiwEzG9Rx35RgBc/edit#) 
- Give feedback
- Let me know if this is something you would like to do at your brigade (if yes, I will share the sidedeck when I finish it by Monday, August 5th 5pm PDT)
- Discuss what the the cons are of using this method.

I am going to workshop this with our team leads on Monday August 5th at our Santa Monica hack night and Tuesday, August 13th at our Downtown LA hack night, to see what their excitement level is and what kind of results we can generate in the 15-20 minutes I think it will take to do this Github meta tagging activity.

**Comment by themightychris** [comment]
Interesting idea, there are some downsides to this approach to consider too though:

- only admins of a repo can edit this information, while anyone can use GitHub's pull-request workflow to propose changes to documentation/metadata stored as a file in the repo. I suspect this approach will hit heavy technical and social "who has authority to improve this?" friction. We might get people to edit this once but the agency to improve and update them will be sparse
- when a repo gets forked, does the info travel with it?
- are we likely to reach the limit of what we can store here relatively early on the way to achieving our ultimate goals? The impact of having to retrain everyone and migrate repos could easily negate any coding or time saved
- it's not clear that this gets us to a first really useful result without code, we very well may still need to write code even for that, and it may not be simpler. IMO avoiding writing code shouldn't be a defining goal anyway

**Comment by ExperimentsInHonesty** [comment]
Hi Chris,

Thanks for reviewing the proposal.

I turned your comment into a numbered list so I could address each item or ask for more info.
1. I think this might need to know more about how your brigade operates its github in order to understand your concern here.  What I can tell you is in my brigade we have a pretty well defined team structure on github.  Here is an example of a team
![image](https://user-images.githubusercontent.com/37763229/62188204-88fb3280-b320-11e9-96d3-674929929155.png)
Any one of the team admins can edit tags, as well as the github owners (me and one other hack night host).  So improving the topic tags or updating them seems easy enough for us to execute.  I look forward to hearing how Philly structures its projects.
2. When a repo gets forked the description goes with it, but the topic tags do not.  Will the new owners have to make new topic tags if they want their project to appear in the search results?  In a word: Yes.  However I see this as a positive, because code forked from one brigade to another won't carry the name of the brigade (or status if we decide to do that) in the topic tag, polluting the quality of the meta data.  
3. Even if this does not end up being the ultimate solution, there is absolutely no waste of time in doing this activity because all projects should be using the description and topic tags.
- for search engine optimization (google, and github search)
- for new people trying to review a brigades github account.
4. 
 - a) I am unsure what criteria you are using to define a useful result.  I think we are getting ready to define that a group, so let's put a pin in this for now and definitely circle back once we have our group criteria.
 - b) How might this effort make getting a useful result more complicated?
 - c) In my conversations with Project Managers (PMs), leadership, tech leads and coders, the only people who care about marketing are the PMs, leadership and marketing.  The github solution proposed gives agency to those people, without removing agency from Tech leads and coders should they want to get involved.  

So to be clear, I am not against a code solution, but I strongly support a path of least effort for MVP that: 
- will easily demonstrate the value of a brigade project index to each brigade individually and the network as a whole.
- has the best chance of being widely used, so we have something to actually get user feedback on
- have ancillary benefits to those who do use it, so that if the project fails to gain traction across the network, the early adopters wont have wasted their time.
- involves a minimal time commitment for each brigade.

**Comment by nikolajbaer** [comment]
Hi Everyone,

I reviewed the proposal. My 2 cents is that we encourage both fully utilizing github meta data (per Bonnie), as well as encourage full specification with the civic.json spec, as that is a richer spec that we have some level of control over (and can potentially be extended to allow for richer features like sibling projects, etc). 

From what I see, both these methods would still require both at the minimum a reporting tool (something I would like to build on beyond my initial analysis script), as well as a non-github formalized index where we can show projects potentially more accurately. An example that comes to mind is the Voter's dashboard currently being worked on at Open San Diego, which involves both a "front-end" repo and a "back-end repo"  that would be good to present in tandem, as well as to point to where these repos were forked from.

For action items, I would propose extending the analysis script to provide a way to summarize and visualize both github and civic.json metadata across all brigades.

Thanks Bonnie for putting this together
Nikolaj

**Comment by ExperimentsInHonesty** [comment]
The consensus was that its worth building out the educational materials and trying it on a brigade by brigade level and I will circle back with everyone when I have the materials completed in a few days.  

To go beyond the following meta data, we will need agreed up taxonomies:
- project description
- brigade and CFA affiliation
- topic

So first phase of this part of the overall project index will just focus on the above meta data and won't include project status, viability, etc.  Although it does include last updated date.

**Comment by gregboyer** [comment]
I just want to add Code for San Francisco to your rollout list @ExperimentsInHonesty :). This seems pretty awesome, and while I see it running into some limits, I think GitHub best practices are synergistic with our overall project.

**Comment by giosce** [comment]
It seems this was an initial conversation, now both brigade-index and civic-tech-index leverage github in different ways as main source of data.
I don't think we need to keep this issue open. Perhaps we should put this in discourse for history.
