### ISSUE TITLE
Prototype: Vacuum network projects + tags into a repo

### ISSUE THREAD

**Issue by themightychris** [codeforamerica/brigade-project-index#19]
Public a network-wide scan of brigade projects + tag into a public git repository

## Scope

- [x] Grab all repos indexed by the CfAPI by crawling from the main brigades list
- [x] Write readable profile files for every discovered project to a canonical `${brigade}/${project}` file in the repo
- [ ] Build profile from composite of github metadata+tagging + any civic.json/publiccode.yaml files

## Past work

- [taxonomy importer that projects wild taxonomy data into public git repos](https://github.com/codeforamerica/civic-tech-taxonomy/blob/master/import.js)
- [CfAPI's scraper](https://github.com/codeforamerica/cfapi/blob/master/run_update.py#L1062-L1085)

**Comment by giosce** [comment]
Closing this, we do have a prototype and we know what to do next (read publiccode.yml and more...).
