### ISSUE TITLE
Build status dashboard of brigade meta data for Brigade Congress

### ISSUE THREAD

**Issue by nikolajbaer** [codeforamerica/brigade-project-index#20]
To motivate and communicate the Brigade Project Index initiative and challenge, we discussed creating a dashboard / interactive visualization for Brigade Congress.

The visualization would show all brigades across the network, their projects and the meta-data/indexed "status" of these projects. It would update as often as possible/reasonable.

Additionally it should be paired with instructions on how to better index projects in your brigade.

Bonus features might be:
1. Filtering / Visualization of tags and taxonomies
2. Suggest one!

References:
https://civictech.guide
(something similar to their homepage map visual maybe)?

**Comment by themightychris** [comment]
@nikolajbaer I can commit to ingesting and normalizing all the projects discoverable through the CfAPI into a repository per #19 

It will be a repo/branch containing a tree of files, where every blob is the repo is a TOML file profiling one project. I'm thinking the paths will probably be `${brigade}/${project}` but that will probably evolve and isn't super important. 

Using that as our source of truth, I could publish from there into a giant JSON file or an SQL script. Do you have any idea yet what would be a good way to hand that off to you for use in a dashboard? If you're building in Node, I could provide library code / examples for reading the DB in its native git format

**Comment by nikolajbaer** [comment]
If you ping me when you have your first run of that repo going, I can definitely work from that.

My goal is to keep this pretty minimal (html page with some d3 ideally). Figuring out when and how often to update might be our biggest concern, but we probably can put something together that runs periodically and gathers what is needed (e.g. a lambda script or whatnot).

**Comment by themightychris** [comment]
@nikolajbaer sounds good. If you beat me to getting started, maybe mock a json file and then I'll target fully populating it with an ongoing process
