### ISSUE TITLE
Make a google doc out of the current documentation so we can review and edit it together

### ISSUE THREAD

**Issue by gregboyer** [codeforamerica/brigade-project-index#21]

**Comment by giosce** [comment]
We do have a google doc with analysis of various taxonomies and additional info/ideas. https://docs.google.com/document/d/1ATKsYsXa6wdQAWv_GxR8i8yF4bmGPYeWO5jJjKZQHDQ/edit#
It is in the cross-brigade-project-index Google folder https://drive.google.com/drive/folders/1yaJe0QQSEw_fKljTJ719o9hQlJAKwGr5

Closing this issue.
