### ISSUE TITLE
Create a pre-congress knowledge assessment

### ISSUE THREAD

**Issue by gregboyer** [codeforamerica/brigade-project-index#23]
Create and send a pre-congress knowledge assessment. E.g. "Where would you go to find out what brigades are working on?"

**Comment by ExperimentsInHonesty** [comment]
Congress is over.  Do you want to do this for summit.  I don't think we need to because everyone at congress seemed to see that there was no location for what other brigades are working on except asking via slack.  Can we close this issue?

**Comment by ExperimentsInHonesty** [comment]
@gregboyer @nikolajbaer see issue #5 which I didn't know about when I led the session at congress.

**Comment by giosce** [comment]
Closing this since two congresses/summits have passed by. If there is any useful documentation from sessions that can be added or referenced here, we can reopen this issue.
