### ISSUE TITLE
Suggestion: Removing code-for-america topic tag display when all results are already code-for-america.  But not when the results are mixed with other code-for-all type results

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [codeforamerica/brigade-project-index#32]
Action to take: add this as an issue to the [project board]. Issue #______

**Comment by themightychris** [comment]
This reminds me, I've been meaning to bring up that the code-for-america tag seems to be headed towards not surviving any purpose. For brigades that want to do tag-based project list management, it's the brigade tag we're pulling projects based on. We're not going to exclude things that have a brigade tag but not the code-for-america tag, and we're also not going to include things that have a code-for-america tag but no brigade.

And if we wanted to have a global tag for non-affiliated projects, code-for-america would be an odd tag for any project not affiliated with a brigade to use. It would be better for `code-for-america` to be the tag cfa itself uses for projects they're publishing as the owning org

So, I suggest we stop promoting folks putting the code-for-america tag on things and instead push the brigades that want to use tagging to build their list to publish what tag they're using and start pushing that

**Comment by ExperimentsInHonesty** [comment]
@themightychris you said "... to be the tag cfa itself uses for projects they're publishing as the owning org" . What is that tag and where can I see it?

**Comment by ExperimentsInHonesty** [comment]
@themightychris can you take your comment above to a new issue and add it to the Overview Kanban in the Topic Tag column, and I'll post my question to you again, and we can discuss further there.  That way this issue stay solely dedicated to the thing that @gregboyer suggested.

**Comment by giosce** [comment]
Closing, please provide more information, actionable tasks if there is something to do.
