### ISSUE TITLE
Validate CfA criteria for support and interest supporting / criteria for supporting Brigade Project Index update

### ISSUE THREAD

**Issue by nikolajbaer** [codeforamerica/brigade-project-index#4]

**Comment by gregboyer** [comment]
Per our discussion last meeting, we can safely assume that the brigade network team at CfA will be supportive (I hear Tom Dooner will be joining our discussion tonight), but that they of course are tight on time and maybe cannot provide material/time. So we can do the work and bring it to them for support!

Anything else on this before it gets closed up?

**Comment by gregboyer** [comment]
Tom Dooner: Is there a way to align this around Brigade Goals? One goal for this quarter for the Brigade Network Team is to help new brigades find projects.

**Comment by giosce** [comment]
Most Brigade leaders I spoke with are supportive. I think I heard also that CfA leadership would be supportive. I think we need to bring the suite of products in better shape and then re-propose for adoption/support.
